-- =============================================================
-- Datos de prueba: Itagüí (comunas + barrios) y 20 personas
-- Fuente: División administrativa de Itagüí (Acuerdo 17, 30/dic/2024)
-- https://es.wikipedia.org/wiki/Itagüí
-- =============================================================
USE bditagui;

INSERT INTO comunas (numero, nombre, descripcion) VALUES
    (1, 'Comuna 1', 'Comuna urbana 1 del municipio de Itagüí'),
    (2, 'Comuna 2', 'Comuna urbana 2 del municipio de Itagüí'),
    (3, 'Comuna 3', 'Comuna urbana 3 del municipio de Itagüí'),
    (4, 'Comuna 4', 'Comuna urbana 4 del municipio de Itagüí'),
    (5, 'Comuna 5', 'Comuna urbana 5 del municipio de Itagüí'),
    (6, 'Comuna 6', 'Comuna urbana 6 del municipio de Itagüí'),
    (7, 'Comuna 7', 'Comuna urbana 7 del municipio de Itagüí')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre), descripcion = VALUES(descripcion);

INSERT INTO barrios (comuna_id, nombre) VALUES
    ((SELECT id FROM comunas WHERE numero = 1), 'Artex'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Zona Industrial No. 1'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Villa Paula'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Los Naranjos'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Centro'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Asturias'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Playa Rica'),
    ((SELECT id FROM comunas WHERE numero = 1), 'San Isidro'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Satexco'),
    ((SELECT id FROM comunas WHERE numero = 1), 'San Juan Bautista'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Las Mercedes'),
    ((SELECT id FROM comunas WHERE numero = 1), 'San José'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Araucaria'),
    ((SELECT id FROM comunas WHERE numero = 1), 'La Gloria'),
    ((SELECT id FROM comunas WHERE numero = 1), 'La Independencia'),
    ((SELECT id FROM comunas WHERE numero = 1), 'Zona Industrial No. 2'),
    ((SELECT id FROM comunas WHERE numero = 1), 'La Santa Cruz'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Camparola'),
    ((SELECT id FROM comunas WHERE numero = 2), 'San Pío X'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Monteverde'),
    ((SELECT id FROM comunas WHERE numero = 2), 'La Palma'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Montesacro'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Las Margaritas'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Samaria'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Santa Ana'),
    ((SELECT id FROM comunas WHERE numero = 2), 'El Palmar'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Samaria Robles del Sur'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Malta'),
    ((SELECT id FROM comunas WHERE numero = 2), 'La Finca'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Santa Catalina'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Yarumito'),
    ((SELECT id FROM comunas WHERE numero = 2), 'Zona Industrial No. 3'),
    ((SELECT id FROM comunas WHERE numero = 3), 'San Francisco'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Triana'),
    ((SELECT id FROM comunas WHERE numero = 3), 'San Antonio'),
    ((SELECT id FROM comunas WHERE numero = 3), 'San Gabriel'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Las Brisas'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Pilsen'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Ditaires'),
    ((SELECT id FROM comunas WHERE numero = 3), 'San Javier'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Bariloche'),
    ((SELECT id FROM comunas WHERE numero = 3), '19 de Abril'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Reserva Campestre'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Villa Lía'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Glorieta Pilsen'),
    ((SELECT id FROM comunas WHERE numero = 3), 'Villas de San Antonio'),
    ((SELECT id FROM comunas WHERE numero = 3), 'San Agustín'),
    ((SELECT id FROM comunas WHERE numero = 4), 'Simón Bolívar'),
    ((SELECT id FROM comunas WHERE numero = 4), 'Colinas del Sur'),
    ((SELECT id FROM comunas WHERE numero = 4), 'La Mayorista'),
    ((SELECT id FROM comunas WHERE numero = 4), 'El Carmelo'),
    ((SELECT id FROM comunas WHERE numero = 4), 'El Guayabo'),
    ((SELECT id FROM comunas WHERE numero = 4), 'San Fernando'),
    ((SELECT id FROM comunas WHERE numero = 4), 'La Esmeralda'),
    ((SELECT id FROM comunas WHERE numero = 4), 'Viviendas del Sur'),
    ((SELECT id FROM comunas WHERE numero = 4), 'La Hortencia'),
    ((SELECT id FROM comunas WHERE numero = 4), 'Villa Ventura'),
    ((SELECT id FROM comunas WHERE numero = 4), 'Santa María No. 2'),
    ((SELECT id FROM comunas WHERE numero = 4), 'Santa María No. 1'),
    ((SELECT id FROM comunas WHERE numero = 4), 'Santa María No. 3'),
    ((SELECT id FROM comunas WHERE numero = 5), 'Balcones de Sevilla'),
    ((SELECT id FROM comunas WHERE numero = 5), 'La Aldea'),
    ((SELECT id FROM comunas WHERE numero = 5), 'Las Américas'),
    ((SELECT id FROM comunas WHERE numero = 5), 'Las Acacias'),
    ((SELECT id FROM comunas WHERE numero = 5), 'El Tablazo'),
    ((SELECT id FROM comunas WHERE numero = 5), 'Loma Linda'),
    ((SELECT id FROM comunas WHERE numero = 5), 'Calatrava'),
    ((SELECT id FROM comunas WHERE numero = 5), 'Terranova'),
    ((SELECT id FROM comunas WHERE numero = 5), 'Ferrara'),
    ((SELECT id FROM comunas WHERE numero = 6), 'Fátima'),
    ((SELECT id FROM comunas WHERE numero = 6), 'El Rosario'),
    ((SELECT id FROM comunas WHERE numero = 6), 'Santa María La Nueva'),
    ((SELECT id FROM comunas WHERE numero = 6), 'La Unión'),
    ((SELECT id FROM comunas WHERE numero = 6), 'El Progreso'),
    ((SELECT id FROM comunas WHERE numero = 6), 'Loma de los Zuleta'),
    ((SELECT id FROM comunas WHERE numero = 6), 'Los Olivares'),
    ((SELECT id FROM comunas WHERE numero = 7), 'Del Valle'),
    ((SELECT id FROM comunas WHERE numero = 7), 'El Porvenir 2'),
    ((SELECT id FROM comunas WHERE numero = 7), 'El Porvenir 1'),
    ((SELECT id FROM comunas WHERE numero = 7), 'La Villas'),
    ((SELECT id FROM comunas WHERE numero = 7), 'San Pablo'),
    ((SELECT id FROM comunas WHERE numero = 7), 'Jardines de San José'),
    ((SELECT id FROM comunas WHERE numero = 7), 'Tierra Verde'),
    ((SELECT id FROM comunas WHERE numero = 7), 'El Arenal')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

INSERT INTO personas
    (tipo_documento, documento, nombres, apellidos, telefono, direccion, barrio_id)
VALUES
    ('CC', '1020440001', 'Juan Pablo', 'Restrepo Mejía', '+57 301 555 1011', 'Calle 43 # 47-11', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 1 AND b.nombre = 'Centro')),
    ('CC', '1020440002', 'María Fernanda', 'Giraldo Zapata', '+57 302 555 1022', 'Calle 44 # 48-12', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 1 AND b.nombre = 'Las Mercedes')),
    ('CC', '1020440003', 'Carlos Andrés', 'Ospina Cardona', '+57 303 555 1033', 'Calle 45 # 49-13', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 2 AND b.nombre = 'Camparola')),
    ('CC', '1020440004', 'Laura Vanessa', 'Vélez Arango', '+57 304 555 1044', 'Calle 46 # 50-14', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 2 AND b.nombre = 'Samaria')),
    ('CC', '1020440005', 'Andrés Felipe', 'Montoya Salazar', '+57 305 555 1055', 'Calle 47 # 51-15', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 3 AND b.nombre = 'Ditaires')),
    ('CC', '1020440006', 'Sara Isabel', 'Correa Londoño', '+57 310 555 1066', 'Calle 48 # 52-16', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 3 AND b.nombre = 'San Gabriel')),
    ('CC', '1020440007', 'Diego Alejandro', 'Uribe Castaño', '+57 311 555 1077', 'Calle 49 # 53-17', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 4 AND b.nombre = 'Simón Bolívar')),
    ('CC', '1020440008', 'Valentina', 'Patiño Quintero', '+57 312 555 1088', 'Calle 50 # 54-18', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 4 AND b.nombre = 'Santa María No. 1')),
    ('CC', '1020440009', 'Sebastián', 'Herrera Ríos', '+57 313 555 1099', 'Calle 51 # 46-19', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 5 AND b.nombre = 'El Tablazo')),
    ('CC', '1020440010', 'Camila Andrea', 'Muñoz Cano', '+57 300 555 1110', 'Calle 52 # 47-20', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 5 AND b.nombre = 'Loma Linda')),
    ('CC', '1020440011', 'Julián Esteban', 'Rojas Sierra', '+57 301 555 1121', 'Calle 53 # 48-21', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 6 AND b.nombre = 'El Rosario')),
    ('CC', '1020440012', 'Daniela', 'Cifuentes Barrios', '+57 302 555 1132', 'Calle 42 # 49-22', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 6 AND b.nombre = 'La Unión')),
    ('CC', '1020440013', 'Miguel Ángel', 'Gaviria Botero', '+57 303 555 1143', 'Calle 43 # 50-23', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 7 AND b.nombre = 'San Pablo')),
    ('CC', '1020440014', 'Natalia', 'Escobar Rendón', '+57 304 555 1154', 'Calle 44 # 51-24', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 7 AND b.nombre = 'Tierra Verde')),
    ('CC', '1020440015', 'Santiago', 'Betancur Gil', '+57 305 555 1165', 'Calle 45 # 52-25', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 3 AND b.nombre = 'Pilsen')),
    ('CC', '1020440016', 'Manuela', 'Castaño Vásquez', '+57 310 555 1176', 'Calle 46 # 53-26', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 4 AND b.nombre = 'San Fernando')),
    ('CC', '1020440017', 'Felipe', 'Arroyave Naranjo', '+57 311 555 1187', 'Calle 47 # 54-27', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 2 AND b.nombre = 'La Finca')),
    ('CC', '1020440018', 'Isabella', 'Mejía Cárdenas', '+57 312 555 1198', 'Calle 48 # 46-28', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 6 AND b.nombre = 'Fátima')),
    ('CC', '1020440019', 'Samuel', 'Londoño Restrepo', '+57 313 555 1209', 'Calle 49 # 47-29', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 5 AND b.nombre = 'Calatrava')),
    ('CC', '1020440020', 'Gabriela', 'Suárez Marín', '+57 300 555 1220', 'Calle 50 # 48-30', (SELECT b.id FROM barrios b JOIN comunas c ON b.comuna_id = c.id WHERE c.numero = 1 AND b.nombre = 'San José'))
ON DUPLICATE KEY UPDATE documento = VALUES(documento);

